set_property IOSTANDARD LVCMOS33 [get_ports {color_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {color_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property IOSTANDARD LVCMOS33 [get_ports down]

set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN N17 [get_ports down]
set_property PACKAGE_PIN M18 [get_ports up]
set_property PACKAGE_PIN P17 [get_ports left]
set_property PACKAGE_PIN M17 [get_ports right]
set_property PACKAGE_PIN P18 [get_ports rst]

set_property PACKAGE_PIN T10 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN R10 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN K16 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN T11 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN L18 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN B11 [get_ports hsync]
set_property PACKAGE_PIN B12 [get_ports vsync]

set_property PACKAGE_PIN A4 [get_ports {color_out[11]}]
set_property PACKAGE_PIN C5 [get_ports {color_out[10]}]
set_property PACKAGE_PIN B4 [get_ports {color_out[9]}]
set_property PACKAGE_PIN A3 [get_ports {color_out[8]}]
set_property PACKAGE_PIN A6 [get_ports {color_out[7]}]
set_property PACKAGE_PIN B6 [get_ports {color_out[6]}]
set_property PACKAGE_PIN A5 [get_ports {color_out[5]}]
set_property PACKAGE_PIN C6 [get_ports {color_out[4]}]
set_property PACKAGE_PIN D8 [get_ports {color_out[3]}]
set_property PACKAGE_PIN D7 [get_ports {color_out[2]}]
set_property PACKAGE_PIN C7 [get_ports {color_out[1]}]
set_property PACKAGE_PIN B7 [get_ports {color_out[0]}]

set_property PACKAGE_PIN J17 [get_ports {sel[0]}]
set_property PACKAGE_PIN J18 [get_ports {sel[1]}]
set_property PACKAGE_PIN T9 [get_ports {sel[2]}]
set_property PACKAGE_PIN J14 [get_ports {sel[3]}]
set_property PACKAGE_PIN P14 [get_ports {sel[4]}]
set_property PACKAGE_PIN T14 [get_ports {sel[5]}]
set_property PACKAGE_PIN K2 [get_ports {sel[6]}]
set_property PACKAGE_PIN U13 [get_ports {sel[7]}]